services:

  nextjs:
    image: node:22-alpine
    container_name: nextjs-dev

    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

    working_dir: /app

    volumes:
      - ./app:/app

    ports:
      - "3000:3000"
      - "9229:9229"
      - "5555:5555"
      - "51212:51212"

    stdin_open: true
    tty: true

    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schema_versioning

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: